export default [
  "", // nothing
  "", // transparent
  "POST_FAIL",
  "UNDEFINED",
  "q",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  ",", // 0x10
  "n",
  "o",
  "p",
  "a",
  "r",
  "s",
  "t",
  "u",
  "v",
  "z",
  "x",
  "y",
  "w",
  "&",
  "é",
  '"', // 0x20
  "'",
  "(",
  "§",
  "è",
  "!",
  "ç",
  "à",
  "ENTER",
  "ESC",
  "BKSP",
  "TAB",
  "SPACE",
  ")",
  "-",
  "^",
  "$", // 0x30
  "???",
  "`",
  "m",
  "ù",
  "@",
  ";",
  ":",
  "=",
  "⇪",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7", // 0x40
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "PRINT_SCREEN",
  "SCROLL_LOCK",
  "PAUSE",
  "INSERT",
  "HOME",
  "PAGE_UP",
  "DEL",
  "END",
  "PAGE_DOWN",
  "RIGHT",
  "LEFT", // 0x50
  "DOWN",
  "UP",
  "NUM_LOCK",
  "KP_SLASH",
  "KP_ASTERISK",
  "KP_MINUS",
  "KP_PLUS",
  "KP_ENTER",
  "KP_1",
  "KP_2",
  "KP_3",
  "KP_4",
  "KP_5",
  "KP_6",
  "KP_7",
  "KP_8", // 0x60
  "KP_9",
  "KP_0",
  "KP_DOT",
  "<",
  "APPLICATION",
  "KB_POWER",
  "KP_EQUAL",
  "F13",
  "F14",
  "F15",
  "F16",
  "F17",
  "F18",
  "F19",
  "F20",
  "F21", // 0x70
  "F22",
  "F23",
  "F24",
  "EXECUTE",
  "HELP",
  "MENU",
  "SELECT",
  "STOP",
  "AGAIN",
  "UNDO",
  "CUT",
  "COPY",
  "PASTE",
  "FIND",
  "KB_MUTE",
  "KB_VOLUME_UP", // 0x80
  "KB_VOLUME_DOWN",
  "LOCKING_CAPS_LOCK",
  "LOCKING_NUM_LOCK",
  "LOCKING_SCROLL_LOCK",
  "KP_COMMA",
  "KP_EQUAL_AS400",
  "INTERNATIONAL_1",
  "INTERNATIONAL_2",
  "INTERNATIONAL_3",
  "INTERNATIONAL_4",
  "INTERNATIONAL_5",
  "INTERNATIONAL_6",
  "INTERNATIONAL_7",
  "INTERNATIONAL_8",
  "INTERNATIONAL_9",
  "LANGUAGE_1", // 0x90
  "LANGUAGE_2",
  "LANGUAGE_3",
  "LANGUAGE_4",
  "LANGUAGE_5",
  "LANGUAGE_6",
  "LANGUAGE_7",
  "LANGUAGE_8",
  "LANGUAGE_9",
  "ALTERNATE_ERASE",
  "SYSTEM_REQUEST",
  "CANCEL",
  "CLEAR",
  "PRIOR",
  "RETURN",
  "SEPARATOR",
  "OUT", // 0xA0
  "OPER",
  "CLEAR_AGAIN",
  "CRSEL",
  "EXSEL",
];

export const shifted = [
  "", // nothing
  "", // transparent
  "POST_FAIL",
  "UNDEFINED",
  "Q",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "?", // 0x10
  "N",
  "O",
  "P",
  "A",
  "R",
  "S",
  "T",
  "U",
  "V",
  "Z",
  "X",
  "Y",
  "Z",
  "1",
  "2",
  "3", // 0x20
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  null, // "⏎",
  null, //"ESC",
  null, //"←",
  null, //"⇥",
  null, //"⎵",
  "°",
  "_",
  "¨",
  "*", // 0x30
  "#",
  ">",
  "M",
  "%",
  "#",
  ".",
  "/",
  "+",
  "⇪",
  null, //"F1",
  null, //"F2",
  null, //"F3",
  null, //"F4",
  null, //"F5",
  null, //"F6",
  null, //"F7", // 0x40
  null, //"F8",
  null, //"F9",
  null, //"F10",
  null, //"F11",
  null, //"F12",
  null, //"PRINT_SCREEN",
  null, //"SCROLL_LOCK",
  null, //"PAUSE",
  null, //"INSERT",
  null, //"HOME",
  null, //"↥",
  null, //"DEL",
  null, //"END",
  null, //"↧",
  null, //"→",
  null, //"←", // 0x50
  null, //"↓",
  null, //"↑",
  null, //"NUM_LOCK",
  null, //"KP_SLASH",
  null, //"KP_ASTERISK",
  null, //"KP_MINUS",
  null, //"KP_PLUS",
  null, //"KP_ENTER",
  null, //"KP_1",
  null, //"KP_2",
  null, //"KP_3",
  null, //"KP_4",
  null, //"KP_5",
  null, //"KP_6",
  null, //"KP_7",
  null, //"KP_8", // 0x60
  null, //"KP_9",
  null, //"KP_0",
  null, //"KP_DOT",
  ">",
  null, //"APPLICATION",
  null, //"KB_POWER",
  null, //"KP_EQUAL",
  null, //"F13",
  null, //"F14",
  null, //"F15",
  null, //"F16",
  null, //"F17",
  null, //"F18",
  null, //"F19",
  null, //"F20",
  null, //"F21", // 0x70
  null, //"F22",
  null, //"F23",
  null, //"F24",
  null, //"EXECUTE",
  null, //"HELP",
  null, //"MENU",
  null, //"SELECT",
  null, //"STOP",
  null, //"AGAIN",
  null, //"UNDO",
  null, //"CUT",
  null, //"COPY",
  null, //"PASTE",
  null, //"FIND",
  null, //"KB_MUTE",
  null, //"KB_VOLUME_UP", // 0x80
  null, //"KB_VOLUME_DOWN",
  null, //"LOCKING_CAPS_LOCK",
  null, //"LOCKING_NUM_LOCK",
  null, //"LOCKING_SCROLL_LOCK",
  null, //"KP_COMMA",
  null, //"KP_EQUAL_AS400",
  null, //"INTERNATIONAL_1",
  null, //"INTERNATIONAL_2",
  null, //"INTERNATIONAL_3",
  null, //"INTERNATIONAL_4",
  null, //"INTERNATIONAL_5",
  null, //"INTERNATIONAL_6",
  null, //"INTERNATIONAL_7",
  null, //"INTERNATIONAL_8",
  null, //"INTERNATIONAL_9",
  null, //"LANGUAGE_1", // 0x90
  null, //"LANGUAGE_2",
  null, //"LANGUAGE_3",
  null, //"LANGUAGE_4",
  null, //"LANGUAGE_5",
  null, //"LANGUAGE_6",
  null, //"LANGUAGE_7",
  null, //"LANGUAGE_8",
  null, //"LANGUAGE_9",
  null, //"ALTERNATE_ERASE",
  null, //"SYSTEM_REQUEST",
  null, //"CANCEL",
  null, //"CLEAR",
  null, //"PRIOR",
  null, //"RETURN",
  null, //"SEPARATOR",
  null, //"OUT", // 0xA0
  null, //"OPER",
  null, //"CLEAR_AGAIN",
  null, //"CRSEL",
  null, //"EXSEL",
];

export const alted = [
  "", // nothing
  "", // transparent
  "POST_FAIL",
  "UNDEFINED",
  "‡",
  "ß",
  "©",
  "∂",
  "ê",
  "ƒ",
  "ﬁ",
  "Ì",
  "î",
  "Ï",
  "È",
  "¬",
  "∞", // 0x10
  "~",
  "œ",
  "π",
  "æ",
  "®",
  "Ò",
  "†",
  "º",
  "◊",
  "Â",
  "≈",
  "Ú",
  "Â",
  "´",
  "ë",
  "“", // 0x20
  "‘",
  "{",
  "§",
  "«",
  "¡",
  "Ç",
  "ø",
  null, //"⏎",
  null, //"ESC",
  null, // "←",
  null, //"⇥",
  null, // "⎵",
  "}",
  "—",
  "ô",
  "€", // 0x30
  "???",
  "≤",
  "µ",
  "Ù",
  "•",
  "…",
  "÷",
  "≠",
  null, // "⇪",
  null, // "F1",
  null, // "F2",
  null, // "F3",
  null, // "F4",
  null, // "F5",
  null, // "F6",
  null, // "F7", // 0x40
  null, // "F8",
  null, // "F9",
  null, // "F10",
  null, // "F11",
  null, // "F12",
  null, // "PRINT_SCREEN",
  null, // "SCROLL_LOCK",
  null, // "PAUSE",
  null, // "INSERT",
  null, // "HOME",
  null, // "↥",
  null, // "DEL",
  null, // "END",
  null, // "↧",
  null, // "→",
  null, // "←", // 0x50
  null, // "↓",
  null, // "↑",
  null, // "NUM_LOCK",
  null, // "KP_SLASH",
  null, // "KP_ASTERISK",
  null, // "KP_MINUS",
  null, // "KP_PLUS",
  null, // "KP_ENTER",
  null, // "KP_1",
  null, // "KP_2",
  null, // "KP_3",
  null, // "KP_4",
  null, // "KP_5",
  null, // "KP_6",
  null, // "KP_7",
  null, // "KP_8", // 0x60
  null, // "KP_9",
  null, // "KP_0",
  null, // "KP_DOT",
  null, // "<",
  null, // "APPLICATION",
  null, // "KB_POWER",
  null, // "KP_EQUAL",
  null, // "F13",
  null, // "F14",
  null, // "F15",
  null, // "F16",
  null, // "F17",
  null, // "F18",
  null, // "F19",
  null, // "F20",
  null, // "F21", // 0x70
  null, // "F22",
  null, // "F23",
  null, // "F24",
  null, // "EXECUTE",
  null, // "HELP",
  null, // "MENU",
  null, // "SELECT",
  null, // "STOP",
  null, // "AGAIN",
  null, // "UNDO",
  null, // "CUT",
  null, // "COPY",
  null, // "PASTE",
  null, // "FIND",
  null, // "KB_MUTE",
  null, // "KB_VOLUME_UP", // 0x80
  null, // "KB_VOLUME_DOWN",
  null, // "LOCKING_CAPS_LOCK",
  null, // "LOCKING_NUM_LOCK",
  null, // "LOCKING_SCROLL_LOCK",
  null, // "KP_COMMA",
  null, // "KP_EQUAL_AS400",
  null, // "INTERNATIONAL_1",
  null, // "INTERNATIONAL_2",
  null, // "INTERNATIONAL_3",
  null, // "INTERNATIONAL_4",
  null, // "INTERNATIONAL_5",
  null, // "INTERNATIONAL_6",
  null, // "INTERNATIONAL_7",
  null, // "INTERNATIONAL_8",
  null, // "INTERNATIONAL_9",
  null, // "LANGUAGE_1", // 0x90
  null, // "LANGUAGE_2",
  null, // "LANGUAGE_3",
  null, // "LANGUAGE_4",
  null, // "LANGUAGE_5",
  null, // "LANGUAGE_6",
  null, // "LANGUAGE_7",
  null, // "LANGUAGE_8",
  null, // "LANGUAGE_9",
  null, // "ALTERNATE_ERASE",
  null, // "SYSTEM_REQUEST",
  null, // "CANCEL",
  null, // "CLEAR",
  null, // "PRIOR",
  null, // "RETURN",
  null, // "SEPARATOR",
  null, // "OUT", // 0xA0
  null, // "OPER",
  null, // "CLEAR_AGAIN",
  null, // "CRSEL",
  null, // "EXSEL",
];

export const shiftAlted = [
  "", // nothing
  "", // transparent
  "POST_FAIL",
  "UNDEFINED",
  "Ω",
  "∫",
  "¢",
  "∆",
  "Ê",
  "·",
  "ﬂ",
  "Î",
  "ï",
  "Í",
  "Ë",
  "|",
  "¿", // 0x10
  "ı",
  "Œ",
  "·",
  "Æ",
  "‚",
  "∑",
  "™",
  "ª",
  "√",
  "Å",
  "⁄",
  "Ÿ",
  "›", // z/w
  "´",
  "„",
  "”", // 0x20
  "‘",
  "[",
  "å",
  "»",
  "Û",
  "Á",
  "Ø",
  null, //"⏎",
  null, //"ESC",
  null, // "←",
  null, //"⇥",
  null, // "⎵",
  "]",
  "–",
  "Ô",
  "¥", // 0x30
  "",
  "≥",
  "Ó",
  "‰",
  "#",
  "•",
  "\\",
  "±",
  null, // "⇪",
  null, // "F1",
  null, // "F2",
  null, // "F3",
  null, // "F4",
  null, // "F5",
  null, // "F6",
  null, // "F7", // 0x40
  null, // "F8",
  null, // "F9",
  null, // "F10",
  null, // "F11",
  null, // "F12",
  null, // "PRINT_SCREEN",
  null, // "SCROLL_LOCK",
  null, // "PAUSE",
  null, // "INSERT",
  null, // "HOME",
  null, // "↥",
  null, // "DEL",
  null, // "END",
  null, // "↧",
  null, // "→",
  null, // "←", // 0x50
  null, // "↓",
  null, // "↑",
  null, // "NUM_LOCK",
  null, // "KP_SLASH",
  null, // "KP_ASTERISK",
  null, // "KP_MINUS",
  null, // "KP_PLUS",
  null, // "KP_ENTER",
  null, // "KP_1",
  null, // "KP_2",
  null, // "KP_3",
  null, // "KP_4",
  null, // "KP_5",
  null, // "KP_6",
  null, // "KP_7",
  null, // "KP_8", // 0x60
  null, // "KP_9",
  null, // "KP_0",
  null, // "KP_DOT",
  null, // "<",
  null, // "APPLICATION",
  null, // "KB_POWER",
  null, // "KP_EQUAL",
  null, // "F13",
  null, // "F14",
  null, // "F15",
  null, // "F16",
  null, // "F17",
  null, // "F18",
  null, // "F19",
  null, // "F20",
  null, // "F21", // 0x70
  null, // "F22",
  null, // "F23",
  null, // "F24",
  null, // "EXECUTE",
  null, // "HELP",
  null, // "MENU",
  null, // "SELECT",
  null, // "STOP",
  null, // "AGAIN",
  null, // "UNDO",
  null, // "CUT",
  null, // "COPY",
  null, // "PASTE",
  null, // "FIND",
  null, // "KB_MUTE",
  null, // "KB_VOLUME_UP", // 0x80
  null, // "KB_VOLUME_DOWN",
  null, // "LOCKING_CAPS_LOCK",
  null, // "LOCKING_NUM_LOCK",
  null, // "LOCKING_SCROLL_LOCK",
  null, // "KP_COMMA",
  null, // "KP_EQUAL_AS400",
  null, // "INTERNATIONAL_1",
  null, // "INTERNATIONAL_2",
  null, // "INTERNATIONAL_3",
  null, // "INTERNATIONAL_4",
  null, // "INTERNATIONAL_5",
  null, // "INTERNATIONAL_6",
  null, // "INTERNATIONAL_7",
  null, // "INTERNATIONAL_8",
  null, // "INTERNATIONAL_9",
  null, // "LANGUAGE_1", // 0x90
  null, // "LANGUAGE_2",
  null, // "LANGUAGE_3",
  null, // "LANGUAGE_4",
  null, // "LANGUAGE_5",
  null, // "LANGUAGE_6",
  null, // "LANGUAGE_7",
  null, // "LANGUAGE_8",
  null, // "LANGUAGE_9",
  null, // "ALTERNATE_ERASE",
  null, // "SYSTEM_REQUEST",
  null, // "CANCEL",
  null, // "CLEAR",
  null, // "PRIOR",
  null, // "RETURN",
  null, // "SEPARATOR",
  null, // "OUT", // 0xA0
  null, // "OPER",
  null, // "CLEAR_AGAIN",
  null, // "CRSEL",
  null, // "EXSEL",
];
